# используем язык java. Travis CI поддерживает другие языки тоже.
codecov: true
language: java
jdk:
  - openjdk11

addons:
  postgresql: "9.5"
services:
  - postgresql

before_install:
  - psql -c 'create database forum;' -U postgres

    install: true

# используем режим обычного пользователя для сборки проекта.
sudo: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
# Отправлять уведомление на почту vovk.ag747@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -vovk.ag747@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

    global:
      - CODECOV_TOKEN="fe4ab15b-c447-4efb-b2ed-9c92bda2fd99"
